FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build
WORKDIR /src
COPY ["Taskedo.Tasks.Domain/Taskedo.Tasks.Domain.csproj", "Taskedo.Tasks.Domain/"]
COPY ["Taskedo.Tasks.Application/Taskedo.Tasks.Application.csproj", "Taskedo.Tasks.Application/"]
COPY ["Taskedo.Tasks.Database.Context/Taskedo.Tasks.Database.Context.csproj", "Taskedo.Tasks.Database.Context/"]
COPY ["Taskedo.Tasks.Database.Changes/Taskedo.Tasks.Database.Changes.csproj", "Taskedo.Tasks.Database.Changes/"]
COPY ["Taskedo.WebApi/Taskedo.WebApi.csproj", "Taskedo.WebApi/"]
RUN dotnet restore "Taskedo.WebApi/Taskedo.WebApi.csproj" --runtime linux-x64
COPY . .

FROM build AS publish
WORKDIR /src
ARG VERSION=1.0.0.0
RUN dotnet publish "Taskedo.WebApi/Taskedo.WebApi.csproj" -c Release -o /app/publish \
    --no-restore \
    --runtime linux-x64 \
    --self-contained true \
    /p:PublishTrimmed=true \
    /p:PublishSingleFile=true \
    /p:Version=$VERSION

FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-jammy AS final

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
ENV ASPNETCORE_URLS=http://*:8080/
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_PORT=8080
ENV DOTNET_CLI_TELEMETRY_OPTOUT 1
ENV LOGGING__LOGLEVEL__DEFAULT=Information
ENV LOGGING__LOGLEVEL__MICROSOFT=Warning
ENV LOGGING__LOGLEVEL__Microsoft.Hosting.Lifetime=Information

EXPOSE 8080
EXPOSE 443

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./Taskedo.WebApi"]
